allow configurable openshift-web-console image
aerogear/minishift-mobilecore-addon pull request #23
Opened 2018-04-18 15:09 UTC by philbrookes

Deploy custom web-console image.

## Verification steps:
Install this version of the addon into minishift and enable it.
```
minishift config set addon-env CONTAINER_REPO_USERNAME=${DOCKERHUB_USER},CONTAINER_REPO_PASSWORD="${DOCKERHUB_PASSWORD}",CONSOLE_IMAGE=aerogear/origin-web-console:integrations
```
```
minishift stop
minishift delete
minishift start --openshift-version v3.9.0 --service-catalog
```
Deploy fh-sync-server to a project and you should see the integrations section in the overview once fh-sync-server has successfully deployed.

2018-04-19 14:40 UTC, david-martin commented on mobile-core.addon
> +ssh while [ $(oc get pods -n openshift-web-console | grep "webconsole" | grep -v "deploy" | grep "Running" | wc -l) -eq 0 ]; do sleep 2; done
we could make the query more resilient by using labels to find the pod.

e.g. 
```
oc get pods -n openshift-web-console -l app=openshift-web-console --template "{{(index .items 0).status.phase}}"  | grep Running

Running
```

2018-04-19 14:57 UTC, david-martin commented on docs/create-custom-console-container.adoc
> +CONSOLE_REPO_PATH=path/to/origin-web-console make vendor-console
This cmd gives an error about a missing dep

```
CONSOLE_REPO_PATH=~/work/origin-web-console make vendor-console
GIT_REF= CONSOLE_REPO_PATH=/home/dmartin/work/origin-web-console hack/vendor-console.sh
Making sure go-bindata binary has been built...
go-bindata/main.go:15:2: cannot find package "github.com/jteeuwen/go-bindata" in any of:
	/usr/lib/golang/src/github.com/jteeuwen/go-bindata (from $GOROOT)
	/home/dmartin/go/src/github.com/jteeuwen/go-bindata (from $GOPATH)
[ERROR] PID 11454: hack/vendor-console.sh:23: `go install ./...` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/vendor-console.sh:23: `go install ./...`
[INFO]   Exiting with code 1.
make: *** [Makefile:137: vendor-console] Error 1
```

2018-04-19 15:57 UTC, david-martin approved these changes
Approved. Tried running a custom image locally, and building a custom image. Both are good.

Good to merge if we get a 2nd ack from@sedroche

2018-04-20 08:10 UTC, maleck13 commented on docs/create-custom-console-container.adoc
> +Now you are ready to start Minishift with the custom container
Is there a link to this doc somewhere, I don't see it?

2018-04-20 08:11 UTC, maleck13 requested changes
I think we should very clearly call out in the README:

Setting up the mobile addon to view the latest UI changes with a set of instructions under that heading

2018-04-20 09:17 UTC, merged